routes/links_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
import sqlite3

links_bp = Blueprint('links_bp', __name__)

# TODO Remove the palavra_chave database and include a new column in the links database to store the Connection required, related to a new table pre requirements 
@links_bp.route('/')
def index():
    format = request.args.get('format', default='html')  # Obtém o parâmetro 'format', padrão para 'html' se não estiver presente
    # Lógica para exibir todas as links
    conn = sqlite3.connect('links.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id, url, descricao, palavras_chave FROM links')
    rows = cursor.fetchall()
    conn.close()

    links = [{'id': row[0], 'url': row[1], 'descricao': row[2].replace('\n', ' '), 'palavras_chave': row[3]} for row in rows] # Criar lista de objetos de link
    if format == 'json':
        return jsonify(links)  # Retorna os dados no formato JSON
    
    return render_template('links.html', links=links)
    pass

@links_bp.route('/add',  methods=['GET', 'POST'])
def add_link():
    if request.method == 'POST':
        url = request.form['url'] 
        descricao = request.form['descricao'] 
        palavras_chave = request.form['palavras_chave'] 

        # Lógica para adicionar uma nova link
        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('INSERT INTO links (url, descricao, palavras_chave) VALUES ( ?, ?, ?)', (url, descricao, palavras_chave,))
        conn.commit()
        conn.close()

        # Redirecionamento após adicionar a link
        return redirect(url_for('links_bp.index'))  # Redirecionar para a página de exibição de todas as links

    # Se a requisição não for do tipo POST, retornar um redirecionamento
    return redirect(url_for('links_bp.index'))  # Redirecionar para a página de exibição de todas as links
    pass

@links_bp.route('/edit/<int:link_id>', methods=['GET', 'POST'])
def edit_link(link_id):
    # Lógica para editar uma link
    if request.method == 'POST':
        # Se o formulário foi submetido
        nova_url = request.form['nova_url'] 
        nova_descricao = request.form['nova_descricao'] 
        nova_palavras_chave = request.form['nova_palavras_chave'] 

        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('UPDATE links SET url = ?, descricao = ?, palavras_chave = ? WHERE id = ?', (nova_url, nova_descricao, nova_palavras_chave, link_id,)) # Corrigir a query SQL
        
        conn.commit()
        conn.close()

        return redirect(url_for('links_bp.index'))  # Redirecionar para a página de exibição de todas as links após a edição

    else:
        # Se é uma requisição GET, exibir o formulário de edição
        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('SELECT id, url, descricao, palavras_chave  FROM links WHERE id = ?', (link_id,))
        link = cursor.fetchone()
        conn.close()

        if link:
            return render_template('edit_link.html', link_id=link_id, url=link[1] , descricao=link[2], palavras_chave=link[3])
        else:
            # Se a link com o ID especificado não existir, retornar uma mensagem de erro ou redirecionar para uma página de erro
            return 'link não encontrada', 404
    pass

@links_bp.route('/delete/<int:link_id>')
def delete_link(link_id):
    # Lógica para excluir uma link
    conn = sqlite3.connect('links.db')
    cursor = conn.cursor()
    cursor.execute('DELETE FROM links WHERE id = ?', (link_id,))
    conn.commit()
    conn.close()

    return redirect(url_for('links_bp.index'))  # Redirecionar para a página de exibição de todas as links após a exclusão
    pass

routes/links_tags_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
import sqlite3

links_tags_bp = Blueprint('links_tags_bp', __name__)

@links_tags_bp.route('/')
def index():
    # Lógica para exibir todas as links_tags
    conn = sqlite3.connect('links.db')
    cursor = conn.cursor()
    cursor.execute('''SELECT links_tags.id, links_tags.link_id, links_tags.tag_id, links.palavras_chave, tags.nome
                      FROM links_tags
                   inner join links on links_tags.link_id = links.id
                   inner join tags on links_tags.tag_id = tags.id''')
    link_tag_rows = cursor.fetchall()

    cursor.execute('''SELECT id, palavras_chave FROM links''')
    link_rows = cursor.fetchall()

    cursor.execute('''SELECT id, nome FROM tags''')
    tag_rows = cursor.fetchall()

    conn.close()


    links_tags = [{'id': link_tag_row[0], 'link_id': link_tag_row[1], 'tag_id': link_tag_row[2], 'palavras_chave':link_tag_row[3], 'tagNome':link_tag_row[4]} for link_tag_row in link_tag_rows] # Criar lista de objetos de link_tag

    # Coletar todos os valores em uma lista separada
    links = [{'id': link_row[0], 'url': link_row[1]} for link_row in link_rows]  # Criar lista de pares id e url
    tags = [{'id': tag_row[0], 'nome': tag_row[1]} for tag_row in tag_rows] 

    return render_template('links_tags.html', rows=links_tags,links=links,tags=tags)

@links_tags_bp.route('/add',  methods=['GET', 'POST'])
def add_link_tag():
    if request.method == 'POST':
        link_id = request.form['link_id'] 
        tag_id = request.form['tag_id'] 

        # Lógica para adicionar uma nova link_tag
        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('INSERT INTO links_tags (link_id, tag_id) VALUES (?, ?)', (link_id, tag_id,))
        conn.commit()
        conn.close()

        # Redirecionamento após adicionar a link_tag
        return redirect(url_for('links_tags_bp.index'))  # Redirecionar para a página de exibição de todas as links_tags

    # Se a requisição não for do tipo POST, retornar um redirecionamento
    return redirect(url_for('links_tags_bp.index'))  # Redirecionar para a página de exibição de todas as links_tags

@links_tags_bp.route('/edit/<int:link_id>', methods=['GET', 'POST'])
def edit_link_tag(link_tag_id):
    # Lógica para editar uma link_tag
    if request.method == 'POST':
        link_id = request.form['link_id'] 
        tag_id = request.form['tag_id'] 

        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('UPDATE links_tags SET link_id = ?, tag_id = ? WHERE id = ?', (link_id, tag_id, link_tag_id,))
        conn.commit()
        conn.close()

        return redirect(url_for('links_tags_bp.index'))  # Redirecionar para a página de exibição de todas as links_tags após a edição

    else:
        # Se é uma requisição GET, exibir o formulário de edição
        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('SELECT id, link_id, tag_id FROM links_tags WHERE id = ?', (link_tag_id,))
        link_tag = cursor.fetchone()
        conn.close()

        if link_tag:
            return render_template('edit_link_tag.html', link_tag_id=link_tag_id, link_id=link_tag[1], tag_id=link_tag[2])
        else:
            # Se a link_tag com o ID especificado não existir, retornar uma mensagem de erro ou redirecionar para uma página de erro
            return 'link_tag não encontrada', 404

@links_tags_bp.route('/delete/<int:link_id>')
def delete_link_tag(link_id):
    # Lógica para excluir uma link_tag
    conn = sqlite3.connect('links.db')
    cursor = conn.cursor()
    cursor.execute('DELETE FROM links_tags WHERE id = ?', (link_id,))
    conn.commit()
    conn.close()

    return redirect(url_for('links_tags_bp.index'))  # Redirecionar para a página de exibição de todas as links_tags após a exclusão

routes/tags_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
import sqlite3

tags_bp = Blueprint('tags_bp', __name__)

@tags_bp.route('/')
def index():
    # Lógica para exibir todas as tags
    conn = sqlite3.connect('links.db')
    cursor = conn.cursor()
    cursor.execute('SELECT id, nome FROM tags')
    rows = cursor.fetchall()
    conn.close()

    tags = [{'id': row[0], 'nome': row[1]} for row in rows]  # Criar lista de objetos de tag
    return render_template('tags.html', tags=tags)
    pass

@tags_bp.route('/add', methods=['POST'])
def add_tag():
    if request.method == 'POST':
        nome = request.form['nova_tag']  # Supondo que o formulário HTML tenha um campo 'nome'

        # Lógica para adicionar uma nova tag
        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('INSERT INTO tags (nome) VALUES (?)', (nome,))
        conn.commit()
        conn.close()

        # Redirecionamento após adicionar a tag
        return redirect(url_for('tags_bp.index'))  # Redirecionar para a página de exibição de todas as tags

    # Se a requisição não for do tipo POST, retornar um redirecionamento
    return redirect(url_for('tags_bp.index'))  # Redirecionar para a página de exibição de todas as tags
    pass

@tags_bp.route('/edit/<int:tag_id>', methods=['GET', 'POST'])
def edit_tag(tag_id):
    # Lógica para editar uma tag
    if request.method == 'POST':
        # Se o formulário foi submetido
        novo_nome = request.form['novo_nome']  # Supondo que o formulário tenha um campo 'novo_nome'

        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('UPDATE tags SET nome = ? WHERE id = ?', (novo_nome, tag_id))
        conn.commit()
        conn.close()

        return redirect(url_for('tags_bp.index'))  # Redirecionar para a página de exibição de todas as tags após a edição

    else:
        # Se é uma requisição GET, exibir o formulário de edição
        conn = sqlite3.connect('links.db')
        cursor = conn.cursor()
        cursor.execute('SELECT nome FROM tags WHERE id = ?', (tag_id,))
        tag = cursor.fetchone()
        conn.close()

        if tag:
            return render_template('edit_tag.html', tag_id=tag_id, nome=tag[0])
        else:
            # Se a tag com o ID especificado não existir, retornar uma mensagem de erro ou redirecionar para uma página de erro
            return 'Tag não encontrada', 404
    pass

@tags_bp.route('/delete/<int:tag_id>')
def delete_tag(tag_id):
    # Lógica para excluir uma tag
    conn = sqlite3.connect('links.db')
    cursor = conn.cursor()
    cursor.execute('DELETE FROM tags WHERE id = ?', (tag_id,))
    conn.commit()
    conn.close()

    return redirect(url_for('tags_bp.index'))  # Redirecionar para a página de exibição de todas as tags após a exclusão
    pass

templates/base.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ACMS{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Menu</h1>
        <nav>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/links">Links</a></li>
                <li><a href="/tags">Tags</a></li>
                <li><a href="/links_tags">Links e Tags</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

templates/edit_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Link</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="title">Edit Link</h1>
        <form action="{{ url_for('links_bp.edit_link', link_id=link_id) }}" method="POST" class="form">
            <label for="nova_url" class="label">New URL:</label>
            <input type="text" id="nova_url" name="nova_url" value="{{ url }}" required class="input"> <br>
            
            <label for="nova_descricao" class="label">New description:</label>
            <textarea id="nova_descricao" name="nova_descricao" required>{{ descricao }} </textarea><br><br>            
        
            <label for="nova_palavras_chave" class="label">New name:</label>
            <input type="text" id="nova_palavras_chave" name="nova_palavras_chave" value="{{ palavras_chave }}" required class="input"><br>
        
            <input type="submit" value="Save" class="button">
        </form>
    </div>
</body>
</html>

templates/edit_tag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Tag</title>
</head>
<body>
    <h1>Editar Tag</h1>

    <form action="{{ url_for('tags_bp.edit_tag', tag_id=tag_id) }}" method="post">
        <label for="novo_nome">Novo Nome da Tag:</label><br>
        <input type="text" id="novo_nome" name="novo_nome" value="{{ nome }}" required><br><br>
        <input type="submit" value="Salvar Alterações">
    </form>
</body>
</html>

templates/links.html
{% extends "base.html" %}

{% block title %}Links - Minha Aplicação{% endblock %}

{% block content %}
    <h2>Add new link:</h2>
    <form method="POST" action="{{ url_for('links_bp.add_link') }}">
        <label for="url">URL:</label><br>
        <input type="text" id="url" name="url" required><br><br>
        
        <label for="descricao">Description:</label><br>
        <textarea id="descricao" name="descricao" required></textarea><br><br>
        
        <label for="palavras_chave">Name:</label><br>
        <input type="text" id="palavras_chave" name="palavras_chave" required><br><br>        

        <button type="submit">Add</button>
    </form>
    <h2>Links:</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>URL</th>
                <th>Description</th>
                <th>edit</th>
                <th>delete</th>
            </tr>
        </thead>
        <tbody>
            {% for link in links %}
                <tr>
                    <td>{{ link.id }}</td>
                    <td>{{ link.palavras_chave }}</td>
                    <td><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></td>
                    <td>{{ link.descricao }}</td>
                    <td><a href="{{ url_for('links_bp.edit_link', link_id=link.id) }}">Editar</a></td>
                    <td><a href="{{ url_for('links_bp.delete_link', link_id=link.id) }}">Excluir</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/links_tags.html
{% extends "base.html" %}
{% block title %}Links e Tags{% endblock %}

{% block content %}
    <h1>Links e Tags</h1>
    <!-- Adjust links and tabs -->
    <!-- Formulário de inserção de nova links_tags -->
    <h2>Add links tags relationship</h2>
    <form action="{{ url_for('links_tags_bp.add_link_tag') }}" method="post">
        <label for="link_id">Link:</label>
        <select id="link_id" name="link_id">
            {% for link in links %}
                <option value="{{ link.id }}">{{ link.url }}</option>
            {% endfor %}
        </select><br><br>

        <label for="tag_id">Tag:</label>
        <select id="tag_id" name="tag_id">
            {% for tag in tags %}
                <option value="{{ tag.id }}">{{ tag.nome }}</option>
            {% endfor %}
        </select><br><br>

        <input type="submit" value="Adicionar relacionamento">
    </form>

    <br>

    <!-- Adjust this class -->
    <!-- Tabela de links_tags existentes -->
    <table border="1">
        <thead>
            <tr>
                <th>Link ID</th>
                <th>Link</th>
                <th>Tag ID</th>
                <th>Tag</th>
                <th>Editar</th>
                <th>Excluir</th>
            </tr>
        </thead>
        <tbody>
            {% for row in rows %}
                <tr>
                    <td>{{ row.link_id }}</td>
                    <td>{{ row.palavras_chave }}</td>
                    <td>{{ row.tag_id }}</td>
                    <td>{{ row.tagNome }}</td>
                    <td><a href="{{ url_for('links_tags_bp.edit_link_tag', link_id=row.id) }}">Editar</a></td>
                    <td><a href="{{ url_for('links_tags_bp.delete_link_tag', link_id=row.id) }}">Excluir</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/pagina_links.html
{% extends "base.html" %}
{% block title %}Links da Instituição{% endblock %}

{% block content %}
    <h1>List of content </h1>
    
    <!-- Campo de busca por palavra-chave -->
    <input type="text" id="searchInput" placeholder="Type...">

    <!-- Menu suspenso para escolha do campo de filtro -->
    <select id="searchField">
        <option value="descricao">Description</option>
        <option value="palavras_chave">Keyword</option>
        <option value="url">URL</option>
    </select>

    <!-- Tabela para exibir os links -->
    <table id="linkTable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>URL</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody id="linkList">
            {% for link in links %}
                <tr>
                    <td>{{ link.id }}</td>
                    <td>{{ link.palavras_chave }}</td>
                    <td><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></td>
                    <td>{{ link.descricao }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            fetchLinks(); // Chama a função fetchLinks() quando o DOM é carregado
        });

        // Função para buscar os links da API
        function fetchLinks() {
            fetch('/links?format=json') 
                .then(response => response.json())
                .then(links => renderLinks(links))
                .catch(error => console.error('Erro ao buscar os links:', error));
        }

        // Função para renderizar os links
        function renderLinks(links) {
            var linkList = document.getElementById("linkList");
            linkList.innerHTML = ""; // Limpa a lista de links antes de renderizar

            var searchTerm = document.getElementById("searchInput").value.toLowerCase();
            var searchField = document.getElementById("searchField").value; // Obtém o campo de filtro selecionado

            // Filtra os links com base no campo escolhido e na palavra-chave
            var filteredLinks = links.filter(function(link) {
                return link[searchField].toLowerCase().includes(searchTerm);
            });

            // Adiciona links filtrados à lista
            filteredLinks.forEach(function(link) {
                var row = document.createElement("tr");
                
                var idCell = document.createElement("td");
                idCell.textContent = link.id;
                row.appendChild(idCell);

                var urlCell = document.createElement("td");
                var urlLink = document.createElement("a");
                urlLink.href = link.url;
                urlLink.target = "_blank";
                urlLink.textContent = link.url;
                urlCell.appendChild(urlLink);
                row.appendChild(urlCell);

                var descricaoCell = document.createElement("td");
                descricaoCell.textContent = link.descricao;
                row.appendChild(descricaoCell);

                var palavrasChaveCell = document.createElement("td");
                palavrasChaveCell.textContent = link.palavras_chave;
                row.appendChild(palavrasChaveCell);

                linkList.appendChild(row);
            });
        }

        // Chama a função renderLinks quando o usuário digita no campo de busca
        document.getElementById("searchInput").addEventListener("input", function() {
            fetchLinks();
        }); 

        // Chama a função renderLinks quando o usuário seleciona um campo de filtro
        document.getElementById("searchField").addEventListener("change", function() {
            fetchLinks();
        });
    </script>
{% endblock %}

templates/tags.html
{% extends 'base.html' %}

{% block title %}Tags - Minha Aplicação{% endblock %}

{% block content %}
<h1>Add tag</h1>
    <form method="POST" action="{{ url_for('tags_bp.add_tag') }}">
        <!-- Campo para adicionar nova tag -->
        <label for="nova_tag">New Tag:</label>
        <input type="text" id="nova_tag" name="nova_tag" required>
        <button type="submit">Add</button>
    </form>
    <br>

    <h2>Tags Existentes:</h2>
    <!-- Exibir tags existentes em uma tabela -->
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Edit</th>
                <th>Delete</th>  <!-- Cabeçalho para a coluna de excluir -->
            </tr>
        </thead>
        <tbody>
            {% for tag in tags %}
                <tr>
                    <td>{{ tag.id }}</td>
                    <td>{{ tag.nome }}</td>
                    <td><a href="{{ url_for('tags_bp.edit_tag', tag_id=tag.id) }}">edit</a></td>
                    <td><a href="{{ url_for('tags_bp.delete_tag', tag_id=tag.id) }}">delete</a></td> <!-- Link para a rota de exclusão -->
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}